### ISSUE TITLE
Infografía Ciclo de vida de Software.

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-Yabin-2021#2]
Les anexo la infografía con su respectiva rúbrica. Recuerde que puede ver el PDF en el inicio de código de repositorio.

[Infografía del ciclo de vida de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Yabin-2021/files/7171606/Infografia.del.ciclo.de.vida.de.Software.pdf)

[1. Rubrica para infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Yabin-2021/files/7171614/1.Rubrica.para.infografia.pdf)

**Comment by carlos-chrs** [comment]
calificado
94= 18.8
Hace falta mas información

**Comment by josealfredo79** [comment]
Bien hecho y revisado
